development:
  adapter: mysql2
  database: SDTN
  username: sdtn
  password: sdtn
  host: 127.0.0.1
# development:
#   adapter: mysql2
#   database: tsdn
#   username: dpi
#   password: dpi
#   host: 132.122.237.248
